# Numpy

In [3]:
import numpy as np
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.array([[1,2,3,],[4,5,6]])

In [6]:
np.shape(b)

(2, 3)

In [7]:
c = np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [8]:
np.shape(c)

(3, 3)

In [9]:
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [10]:
np.shape(d)

(3, 2, 3)

In [11]:
d.dtype

dtype('int64')

In [12]:
a.dtype

dtype('int64')

In [13]:
d.reshape(3,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [14]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [15]:
d.size

18

In [16]:
d.all

<function ndarray.all>

In [17]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [18]:
d.dtype

dtype('int64')

In [19]:
d[2,1,1]

np.int64(17)

In [20]:
a2 = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [21]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
a2 = a2.reshape(3,4)

ValueError: cannot reshape array of size 25 into shape (3,4)

In [21]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a2[::2,1:3]

array([[ 1,  2],
       [ 9, 10]])

In [23]:
a2[0:3,3::]

array([[ 3],
       [ 7],
       [11]])

In [24]:
a2[1:3,1::2]

array([[ 5,  7],
       [ 9, 11]])

In [25]:
a2[0:3,3]

array([ 3,  7, 11])

In [24]:
import numpy as np
a4 = np.arange(27)
print(a4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


3,4,5,10,11

In [25]:
a4 = a4.reshape(3,3,3)

In [26]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

3,8,15,20

In [34]:
a4[0,0,1,2],[1,2,2,0],[0,2,0,2]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

In [ ]:
a = np.array([1])